### ISSUE TITLE
Couldn't reproduce the semantic segmentation experiment

### ISSUE THREAD

**Issue by vic-torr** [ViTAE-Transformer/ViTAE-Transformer-Remote-Sensing#1]
Tried to by simply eval the model, as the notebook 'Semantic segmentatin/demo/inference_demo.ipynb' do. But instead of using restnet, use the uploaded model. 
By providing the config and the model of RSP-ViTAEv2-S-E100, at the notebook, init_segmentor doesn't work, due to configs related with data outside the repo.

I would be pretty happy if you provide some notebook to reproduce that. :)

Best regards

**Comment by DotWang** [comment]
The demo/*.ipynb are carried in the original [mmsegmentation](https://github.com/open-mmlab/mmsegmentation), and we haven't used these yet to test our models.

So maybe your difficuty is how to prepare the potsdam or isaid datasets? For potsdam dataset, you need to download it from: https://www.isprs.org/education/benchmarks/UrbanSemLab/default.aspx, and clip image to patches manually. 
For isaid dataset, you need to download them from: https://captain-whu.github.io/iSAID/dataset.html. Then, you also need to clip them. When preparing the isaid dataset, the officials has provided the Development Kit. For using details you can refer to these repos: https://github.com/Z-Zheng/FarSeg; https://github.com/lxtGH/PFSegNets

Good luck!

**Comment by vic-torr** [comment]
I'm stuck at this point:
KeyError: "EncoderDecoder: 'ViTAE_Window_NoShift_basic is not in the models registry'"
when executing init_segmentor()
I didn't face it on the another models, only on ViTae.

Could you also provide this pre-training of the model? The one from now-MillionAID

**Comment by DotWang** [comment]
Which file is this error report from？

**Comment by DotWang** [comment]
In this repo, we modify the original mmsegmentation and we have registered the ViTAE in https://github.com/ViTAE-Transformer/ViTAE-Transformer-Remote-Sensing/blob/main/Semantic%20Segmentation/mmseg/models/backbones/__init__.py

**Comment by vic-torr** [comment]
> In this repo, we modify the original mmsegmentation and we have registered the ViTAE in https://github.com/ViTAE-Transformer/ViTAE-Transformer-Remote-Sensing/blob/main/Semantic%20Segmentation/mmseg/models/backbones/__init__.py

Thanks! It worked by importing the semantic segmentation project folder as mmsegmentation and uninstalling original mmsegmentation:

pip uninstall mmsegmentation
cd Semantic\ Segmentation
pip install -e .

I'm running from a notebook similar to demo/inference.ipynb, which i made.

**Comment by vic-torr** [comment]
I'd succeeded on using the pre-trained model of ISPRS Potsdam.
Just a last request, could you also provide the pre-trained model to the MillionAID, mentioned on the paper?

**Comment by DotWang** [comment]
Ha?  The relevant remote sensing pretrained models, including ResNet-50-E300, Swin-T-E300 and ViTAEv2-S-E100 have already been released in the home page of this repo, please see [readme](https://github.com/ViTAE-Transformer/ViTAE-Transformer-Remote-Sensing/blob/main/README.md), that is why we created this project.

**Comment by vic-torr** [comment]
Oh, sorry, it was on the root of the project, I didn't saw it. Thanks again! :D

**Comment by DotWang** [comment]
No, the MillionAID is a large-scale dataset for remote sensing scene classification, it doesn't contain any pixel-level labels.  Our purpose is to transfer the weights trained from classification task to a series of remote sensing downstream tasks, such as aerial segmentation and detection.

**Comment by DotWang** [comment]
Oh, we have uploaded the trained upernet weights (fine tuning on potsdam and isaid) in the readme.md of segmentation part, maybe you can manully extract the corresponding weights of backbone part.
