### ISSUE TITLE
变化检测预训练权重问题

### ISSUE THREAD

**Issue by Yeaoer** [ViTAE-Transformer/ViTAE-Transformer-Remote-Sensing#11]
![image](https://user-images.githubusercontent.com/71121922/184540054-57442c52-d7dc-463f-a915-8260434a7740.png)

如图，加载预训练权重，报错，没遇到过这样的错误，还请解惑一下。具体报错：
![image](https://user-images.githubusercontent.com/71121922/184540371-d853c770-64ae-49a9-961c-119dc32b1c4b.png)

**Comment by DotWang** [comment]
抱歉，没遇到过这种问题，猜测有可能是库版本的原因

**Comment by Yeaoer** [comment]
是的，是版本问题，感谢，已解决。
