### ISSUE TITLE
ModuleNotFoundError: No module named 'mmdet.version'

### ISSUE THREAD

**Issue by Ariyl** [ViTAE-Transformer/ViTAE-Transformer-Remote-Sensing#2]
Traceback (most recent call last):
  File "/home/dgx/workspace/cui/ViTAE/tools/train.py", line 13, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/home/dgx/workspace/cui/ViTAE/mmdet/__init__.py", line 1, in <module>
    from .version import __version__, short_version
ModuleNotFoundError: No module named 'mmdet.version'

in the mmdet/__init__.py, I found the code to be written like this

from .version import __version__, short_version

__all__ = ['__version__', 'short_version']

but the .version is not the python file, in the .version file, It is only one line of code
2.2.0

**Comment by DotWang** [comment]
Have you install OBBDetection? You can refer to https://github.com/jbwang1997/OBBDetection/blob/master/docs/install.md for installation. Don't forget to execute `python setup.py develop`

**Comment by Ariyl** [comment]
Thank you for your answer, It is true that I did not recompile the environment in this project because I compiled it in a previous project
