### ISSUE TITLE
Where is the train_labels_{}_{}.txt for scene recognition?

### ISSUE THREAD

**Issue by liulingbo918** [ViTAE-Transformer/ViTAE-Transformer-Remote-Sensing#20]
I am running the code of scene recognition and I have downloaded the AID, UCM, and NWPU datasets from their official webpages.

But there are no train_labels_{}_{}.txt  in these datasets.  Where are train_labels_{}_{}.txt used in your code? 

![image](https://user-images.githubusercontent.com/7027922/207781107-61d797f3-2212-4b7f-8d94-041219490eec.png)

**Comment by DotWang** [comment]
@liulingbo918 https://github.com/ViTAE-Transformer/Remote-Sensing-RVSA/issues/7

**Comment by liulingbo918** [comment]
Thank！
