### ISSUE TITLE
Semantic Segmentation: Potsdam 数据集复现性能差距有点大

### ISSUE THREAD

**Issue by Xie-Muxi-BK** [ViTAE-Transformer/ViTAE-Transformer-Remote-Sensing#21]
未修改 ’upernet_vitae_win_window7_512x512_80k_potsdam_epoch100.py ‘参数，分别使用
RGB+ Label_all，IRRG  + Label_all复现了一遍

我是使用 tools/convert_datasets/potsdam.py 脚本处理的

<img width="746" alt="image" src="https://user-images.githubusercontent.com/97820350/221717098-1d48f659-c575-4b98-8aa9-3119ee8287d2.png">

<img width="743" alt="image" src="https://user-images.githubusercontent.com/97820350/221717166-62f9241d-cdd0-4ed3-8dda-dc264a76b582.png">

config, model
<img width="945" alt="image" src="https://user-images.githubusercontent.com/97820350/221717458-1bc0b9ba-c81f-4051-aa8b-80286aafdc56.png">

结果log和放出的log差距较大

是我处理的Potsdam数据集不对？

**Comment by Xie-Muxi** [comment]
> 

好的，我这几天再试一遍，如果我没理解错的话，使用mmseg自带的划分IRRG + Label_all，是需要将config中的num_classes改为6？

**Comment by DotWang** [comment]
@Xie-Muxi 不，如果你用mmseg那个来处理数据集，想跟文章中一致的话，config里边，num_classes=ignore_index=5应该保持联不变，但是reduce_zero_label要改成True

**Comment by Lee-inso** [comment]
> @Xie-Muxi 不，如果你用mmseg那个来处理数据集，想跟文章中一致的话，config里边，num_classes=ignore_index=5应该保持不变，但是reduce_zero_label要改成True

issus #9 中提到
Hence, in the official potsdam_ori.py, it is ignore_index=255.
They use 'label_noBoundary.zip', whose converted labels (The second one) are [0 1 2 3 4 5 6].
When setting reduce_zero_label=True, the labels are [255 0 1 2 3 4 5], hence the ignore_index was set 255, which set the Undefined background as the ignored category. However, actually both of 5 and 255 should be ignored, isn't it?

In the ViTAE-RS, for 'label_all.zip', whose converted labels are [1 2 3 4 5 6].
When setting 'reduce_zero_label=True', the labels are [0 1 2 3 4 5], hence the ignore_index was set 5.
If 'reduce_zero_label=False', the labels are [1 2 3 4 5 6], the ignored index is 6, however, a 0 is an extra label. Hence, the transformation should be deleted in this repo, to keep the origin [0 1 2 3 4 5], and 5 is the ignored Clutter class and the Undefined background class 6 is not annotated, so ignore_index=5.

reduce_zero_label = False 才会消除class6?

**Comment by Lee-inso** [comment]
> @Xie-Muxi 不，如果你用mmseg那个来处理数据集，想跟文章中一致的话，config里边，num_classes=ignore_index=5应该保持不变，但是reduce_zero_label要改成True

https://github.com/ViTAE-Transformer/ViTAE-Transformer-Remote-Sensing/issues/9#issuecomment-1204984336

https://github.com/ViTAE-Transformer/ViTAE-Transformer-Remote-Sensing/issues/9#issuecomment-1206005832

请问，是3_Ortho_IRPG 还是4_Ortho_RGBIR?

**Comment by DotWang** [comment]
@Lee-inso 参考issue: #9

"
In our implementation, we use '3_Ortho_IRRG.zip' and '5_Labels_all.zip'
"

**Comment by Lee-inso** [comment]
> @Lee-inso 参考issue: #9
> 
> " In our implementation, we use '3_Ortho_IRRG.zip' and '5_Labels_all.zip' "

[Li-Qingyun](https://github.com/Li-Qingyun) commented [on Aug 5, 2022](https://github.com/ViTAE-Transformer/ViTAE-Transformer-Remote-Sensing/issues/9#issuecomment-1206005832)
Oh, the actually used zip is '4_Ortho_RGBIR.zip' and '5_Labels_for_participants_no_Boundary.zip'.

因为这哥们这么说- -
感谢回复，我试一试

**Comment by Xie-Muxi** [comment]
> @Xie-Muxi 不，如果你用mmseg那个来处理数据集，想跟文章中一致的话，config里边，num_classes=ignore_index=5应该保持不变，但是reduce_zero_label要改成True

我又跑了一遍，config中修改num_classes=ignore_index=5，但是log日志中的mIOU整个过程都很低，然后预测的mIOU是1.03，这是为什么呢？

<img width="541" alt="image" src="https://user-images.githubusercontent.com/97820350/222640126-f13cbbc6-1f23-4793-b8ea-a00124c16ec6.png">

**Comment by DotWang** [comment]
@Xie-Muxi reduce_zero_label也得改

**Comment by Xie-Muxi** [comment]
> reduce_zero_label

这个我也是改了的，config脚本中出现了两次这个参数，我都改成了True

**Comment by Xie-Muxi** [comment]
> > reduce_zero_label
> 
> 这个我也是改了的，config脚本中出现了两次这个参数，我都改成了True

有没有可能是我的运行环境有问题？因为这几天我也在复现其他模型，也是这样，貌似第一次跑都没问题，后面跑的时候就会出现train_loss = NaN的问题

**Comment by DotWang** [comment]
@Xie-Muxi 那再检查一下dataset里边的ignore_index，这个再不行我也不知道了

**Comment by Lee-inso** [comment]
> > > reduce_zero_label
> > 
> > 
> > 这个我也是改了的，config脚本中出现了两次这个参数，我都改成了True
> 
> 有没有可能是我的运行环境有问题？因为这几天我也在复现其他模型，也是这样，貌似第一次跑都没问题，后面跑的时候就会出现train_loss = NaN的问题

你这个问题解决了么，如果解决了能分享一下么？

**Comment by DotWang** [comment]
@Xie-Muxi 正好刚给 @Lee-inso 盘了一下，把这个回答给你也贴一下

1. 你用的是哪种数据和标签？
数据有，RGB, IRRG和RGBIR三种
标签有'5_Labels_all.zip'和'5_Labels_all_noBoundary.zip'两种
2. mmseg用'5_Labels_all_noBoundary.zip'，它首先将黑边转换到0，其余颜色转换到1-6，然后reduce_zero_label=True等一通操作后将黑色转到255，然后通过ignore_index=255在算loss时不考虑黑色，然后mmseg直接评测其余六个类别（包含clutter）的精度
3. 我们用'5_Labels_all.zip'，其中无黑色边界，因此我们直接将类别转到0-5（5是clutter），保持reduce_zero_label=False即可，因为遥感论文中通常不考虑cluster，所以我们num_classes=5 ignore_index=5
4. 如果你用'5_Labels_all_noBoundary.zip'，用mmseg转完以后，会有包含黑色和clutter在内七个类别，这样无法同时ignore两个类别
5. 如果你用'5_Labels_all.zip'，用mmseg转完以后，因为无黑色，类别变成1-6，所以需要reduce_zero_label=True，变成0-5，然后你需要同时在config和potsdam_ori.py中(如果你用的话)设置ignore_index=5

你顺着这个思路理一下，看看是哪里设置的不对

**Comment by Xie-Muxi** [comment]
不行诶
“
如果你用'5_Labels_all.zip'，用mmseg转完以后，因为无黑色，类别变成1-6，所以需要reduce_zero_label=True，变成0-5，然后你需要同时在config和potsdam_ori.py中(如果你用的话)设置ignore_index=5

”

mIoU还是会出现几乎为0的情况，前面跑的两次是用什么都没改，用RGB + Labels_all 跑的，mIoU还有60多，后面用IRRG，修改了reduce_zero_label=True，再跑也是发现会出现loss为NaN + mIoU≈0，

我是用MMSEG自带的划分，因为我想做一些控制变量的基准测试，这是我修改的config

```python

norm_cfg = dict(type='SyncBN', requires_grad=True)
model = dict(
    type='EncoderDecoder',
    pretrained=
    '/root/PycharmProjects/xmx/ViTAE-Transformer-Remote-Sensing/SemanticSegmentation/model/rsp-vitaev2-s-ckpt.pth',
    backbone=dict(
        type='ViTAE_Window_NoShift_basic',
        RC_tokens_type=['swin', 'swin', 'transformer', 'transformer'],
        NC_tokens_type=['swin', 'swin', 'transformer', 'transformer'],
        stages=4,
        embed_dims=[64, 64, 128, 256],
        token_dims=[64, 128, 256, 512],
        downsample_ratios=[4, 2, 2, 2],
        NC_depth=[2, 2, 8, 2],
        NC_heads=[1, 2, 4, 8],
        RC_heads=[1, 1, 2, 4],
        mlp_ratio=4.0,
        NC_group=[1, 32, 64, 128],
        RC_group=[1, 16, 32, 64],
        img_size=512,
        window_size=7,
        drop_path_rate=0.3),
    decode_head=dict(
        type='UPerHead',
        in_channels=[64, 128, 256, 512],
        in_index=[0, 1, 2, 3],
        pool_scales=(1, 2, 3, 6),
        channels=512,
        dropout_ratio=0.1,
        num_classes=5,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
        ignore_index=5),
    auxiliary_head=dict(
        type='FCNHead',
        in_channels=256,
        in_index=2,
        channels=256,
        num_convs=1,
        concat_input=False,
        dropout_ratio=0.1,
        num_classes=5,
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        align_corners=False,
        loss_decode=dict(
            type='CrossEntropyLoss', use_sigmoid=False, loss_weight=0.4),
        ignore_index=5),
    train_cfg=dict(),
    test_cfg=dict(mode='whole'))
dataset_type = 'PotsdamDataset'
data_root = '/workspace/CV/users/wangdi153/Dataset/potsdam_dataset/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
crop_size = (512, 512)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', reduce_zero_label=True),
    dict(type='Resize', img_scale=(512, 512), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=(512, 512), cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size=(512, 512), pad_val=0, seg_pad_val=5),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg'])
]
val_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(512, 512),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=None,
        img_ratios=[1.0],
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=4,
    workers_per_gpu=4,
    train=dict(
        type='PotsdamDataset',
        data_root='/root/PycharmProjects/xmx/data/potsdam_all/',
        img_dir='img_dir_IRRG/train',
        ann_dir='ann_dir_IRRG/train',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', reduce_zero_label=True),
            dict(type='Resize', img_scale=(512, 512), ratio_range=(0.5, 2.0)),
            dict(type='RandomCrop', crop_size=(512, 512), cat_max_ratio=0.75),
            dict(type='RandomFlip', prob=0.5),
            dict(type='PhotoMetricDistortion'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size=(512, 512), pad_val=0, seg_pad_val=5),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_semantic_seg'])
        ]),
    val=dict(
        type='PotsdamDataset',
        data_root='/root/PycharmProjects/xmx/data/potsdam_all',
        img_dir='img_dir_IRRG/val',
        ann_dir='ann_dir_IRRG/val',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(512, 512),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]),
    test=dict(
        type='PotsdamDataset',
        data_root='/root/PycharmProjects/xmx/data/potsdam_all',
        img_dir='img_dir_IRRG/val',
        ann_dir='ann_dir_IRRG/val',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=None,
                img_ratios=[1.0],
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ]))
log_config = dict(
    interval=50, hooks=[dict(type='TextLoggerHook', by_epoch=False)])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
cudnn_benchmark = True
optimizer = dict(
    type='AdamW',
    lr=6e-05,
    betas=(0.9, 0.999),
    weight_decay=0.01,
    paramwise_cfg=dict(
        custom_keys=dict(
            absolute_pos_embed=dict(decay_mult=0.0),
            relative_position_bias_table=dict(decay_mult=0.0),
            norm=dict(decay_mult=0.0))))
optimizer_config = dict()
lr_config = dict(
    policy='poly',
    warmup='linear',
    warmup_iters=1500,
    warmup_ratio=1e-06,
    power=1.0,
    min_lr=0.0,
    by_epoch=False)
runner = dict(type='IterBasedRunner', max_iters=80000)
checkpoint_config = dict(by_epoch=False, interval=2000)
evaluation = dict(interval=2000, metric=['mIoU', 'mFscore'], pre_eval=True)
find_unused_parameters = True
work_dir = './work_dirs/upernet_vitae_win_window7_512x512_80k_potsdam_epoch100'
gpu_ids = range(0, 2)
auto_resume = False
```

**Comment by DotWang** [comment]
@Xie-Muxi 你只放config，看不出来的

训练loss是NAN，可能你标签有问题，我建议debug一下，打印出来训练过程中标签和预测值的取值

另外你用的数据集里边也要改啊，像你这种情况，应该改成

```python
# Copyright (c) OpenMMLab. All rights reserved.
from .builder import DATASETS
from .custom import CustomDataset


@DATASETS.register_module()
class PotsdamDataset(CustomDataset):
    """ISPRS Potsdam dataset.

    In segmentation map annotation for Potsdam dataset, 0 is the ignore index.
    ``reduce_zero_label`` should be set to True. The ``img_suffix`` and
    ``seg_map_suffix`` are both fixed to '.png'.
    """
    CLASSES = ('impervious_surface', 'building', 'low_vegetation', 'tree',
               'car', 'clutter')

    PALETTE = [[255, 255, 255], [0, 0, 255], [0, 255, 255], [0, 255, 0],
               [255, 255, 0], [255, 0, 0]]

    def __init__(self, **kwargs):
        super(PotsdamDataset, self).__init__(
            img_suffix='.png',
            seg_map_suffix='.png',
            reduce_zero_label=True,
            ignore_index=5,
            **kwargs)
```

**Comment by Xie-Muxi** [comment]
十分感谢，问题已解决，因为没有修改mmseg中

```python
def __init__(self, **kwargs):
        super(PotsdamDataset, self).__init__(
            img_suffix='.png',
            seg_map_suffix='.png',
            reduce_zero_label=True,
            ignore_index=5,
            **kwargs)
```

**Comment by 1835969208** [comment]
> @Xie-Muxi 你只放config，看不出来的
> 
> 训练loss是NAN，可能你标签有问题，我建议debug一下，打印出来训练过程中标签和预测值的取值
> 
> 另外你用的数据集里边也要改啊，像你这种情况，应该改成
> 
> ```python
> # Copyright (c) OpenMMLab. All rights reserved.
> from .builder import DATASETS
> from .custom import CustomDataset
> 
> 
> @DATASETS.register_module()
> class PotsdamDataset(CustomDataset):
>     """ISPRS Potsdam dataset.
> 
>     In segmentation map annotation for Potsdam dataset, 0 is the ignore index.
>     ``reduce_zero_label`` should be set to True. The ``img_suffix`` and
>     ``seg_map_suffix`` are both fixed to '.png'.
>     """
>     CLASSES = ('impervious_surface', 'building', 'low_vegetation', 'tree',
>                'car', 'clutter')
> 
>     PALETTE = [[255, 255, 255], [0, 0, 255], [0, 255, 255], [0, 255, 0],
>                [255, 255, 0], [255, 0, 0]]
> 
>     def __init__(self, **kwargs):
>         super(PotsdamDataset, self).__init__(
>             img_suffix='.png',
>             seg_map_suffix='.png',
>             reduce_zero_label=True,
>             ignore_index=5,
>             **kwargs)
> ```

这里的img_suffix和seg_map_suffix是不是应该设置为tif呀。因为选用的3_Ortho_IRRG.zip' 和 '5_Labels_all.zip都是tif格式呀

**Comment by 1835969208** [comment]
> > @Xie-Muxi 不，如果你用mmseg那个来处理数据集，想跟文章中一致的话，config里边，num_classes=ignore_index=5应该保持不变，但是reduce_zero_label要改成True
> 
> 我又跑了一遍，config中修改num_classes=ignore_index=5，但是log日志中的mIOU整个过程都很低，然后预测的mIOU是1.03，这是为什么呢？
> 
> <img alt="image" width="755" src="https://user-images.githubusercontent.com/97820350/222640416-54993724-d8f7-4134-857c-10519e9fd064.png">
> 
> <img alt="image" width="541" src="https://user-images.githubusercontent.com/97820350/222640126-f13cbbc6-1f23-4793-b8ea-a00124c16ec6.png">

你好，我是研0的小白。我想问一下我们用mmseg对postdam数据集具体是做什么处理呀。用mmseg训练postdam吗？我的理解认为好像并不是这样的。
