### ISSUE TITLE
What does this ‘BIT’ abbreviation stand for

### ISSUE THREAD

**Issue by zgsxwsdxg** [ViTAE-Transformer/ViTAE-Transformer-Remote-Sensing#6]
hello，great job. What does this ‘BIT’ abbreviation stand for? ths.

**Comment by zgsxwsdxg** [comment]
> 'BIT' is a change detection method, it is proposed by the paper:
> 
> H. Chen, Z. Qi, and Z. Shi, “Remote Sensing Image Change Detection With Transformers,” IEEE Trans. Geosci. Remote Sens., vol. 60, p.3095166, Jan. 2022

Ths，How to understand this sentence ‘For LEVIR dataset, clip the images to 256 × 256 patches and change the structure to’？Whether the aspect provides scripts to process the data？I download levir dataset，but the dataset is 1024 and There is no output folder, just a label folder.

**Comment by DotWang** [comment]
> > 'BIT' is a change detection method, it is proposed by the paper:
> > H. Chen, Z. Qi, and Z. Shi, “Remote Sensing Image Change Detection With Transformers,” IEEE Trans. Geosci. Remote Sens., vol. 60, p.3095166, Jan. 2022
> 
> Ths，How to understand this sentence ‘For LEVIR dataset, clip the images to 256 × 256 patches and change the structure to’？Whether the aspect provides scripts to process the data？I download levir dataset，but the dataset is 1024 and There is no output folder, just a label folder.

You need to crop the images, labels and organize the folders, it is easy to implement.

**Comment by zgsxwsdxg** [comment]
> 



> > > 'BIT' is a change detection method, it is proposed by the paper:
> > > H. Chen, Z. Qi, and Z. Shi, “Remote Sensing Image Change Detection With Transformers,” IEEE Trans. Geosci. Remote Sens., vol. 60, p.3095166, Jan. 2022
> > 
> > 
> > Ths，How to understand this sentence ‘For LEVIR dataset, clip the images to 256 × 256 patches and change the structure to’？Whether the aspect provides scripts to process the data？I download levir dataset，but the dataset is 1024 and There is no output folder, just a label folder.
> 
> You need to crop the images, labels and organize the folders, it is easy to implement.

我的英文不太好，还是中文问下你吧。 就是裁切确实容易实现，我不太明白的是：如果随机裁切，那么每个人的样本不一样，训练的模型MAP和paper是否有大的gap，如果有大的gap，怎么确定问题在哪？怎么能排除不是裁切的问题？你是随机裁切的么？谢谢

**Comment by DotWang** [comment]
你说的随机裁剪是啥意思，这个数据集是1024*1024的，讲道理你裁剪成256*256是不用设置overlap的，而且这个数据集训练集验证集和测试集是固定的啊，不存在什么随机性吧

**Comment by DotWang** [comment]
我貌似懂了，你的意思是训练过程中在数据增强部分随机裁剪？那貌似不太行，这个LEVIR数据集应该是先裁剪，变成图像尺寸为256*256的新数据集，再用这个整理好的新数据集拿去训练
