### ISSUE TITLE
change detection

### ISSUE THREAD

**Issue by zgsxwsdxg** [ViTAE-Transformer/ViTAE-Transformer-Remote-Sensing#7]
我在运行python eval.py \
--backbone 'swin' --dataset 'levir' --mode 'rsp_300' \
--path [model path] 实例时报错如下：

Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2

请问你们用的pytorch那个版本，change detection 我安装按照
https://github.com/likyoo/Siam-NestedUNet/blob/master/README.md
Requirements
Python 3.6

Pytorch 1.4

torchvision 0.5.0

# other packages needed
pip install opencv-python tqdm tensorboardX sklearn

帮忙分析下，谢谢了。

**Comment by DotWang** [comment]
pytorch 1.9+cu111

**Comment by zgsxwsdxg** [comment]
> python 3.8
> 
> pytorch 1.9+cu111
> 
> torchvision 0.9.0
> 
> 剩下那几个包无脑装就行，tensorboard是1.15，不过我没看过那些曲线，你也可以不装，把相关语句注释掉

这样的话，你的change dection目录中的readme中安装说明容易迷惑，谢谢！

**Comment by DotWang** [comment]
是这样，我这边后来换了服务器，也换了环境，发你这个是我现在用的，也能跑起来这套代码，而readme.md里边是SNUNet官方的，因为这套代码框架实际上是SNUNet的，但是我把网络部分换成了BIT，然后优化也是按照BIT的来，我们的方法主要是将BIT的backbone更换为了ViTAEv2-S

**Comment by DotWang** [comment]
不过我估计哈，你还是用新一点的pytorch版本吧，可能transformer中的一些函数只有新一点的pytorch有，也谢谢你的提醒，我去改一下说明文件

**Comment by zgsxwsdxg** [comment]
> 不过我估计哈，你还是用新一点的pytorch版本吧，可能transformer中的一些函数只有新一点的pytorch有，也谢谢你的提醒，我去改一下说明文件

我运行还是出错了， AttributeError: 'DropPath' object has no attribute 'scale_by_keep'
能否详细说明pytorch和python版本号，不仅主版本号还包括子版本号，谢谢您！

我用的是python3.6.8  pytorch1.9.0

**Comment by DotWang** [comment]
> > 不过我估计哈，你还是用新一点的pytorch版本吧，可能transformer中的一些函数只有新一点的pytorch有，也谢谢你的提醒，我去改一下说明文件
> 
> 我运行还是出错了， AttributeError: 'DropPath' object has no attribute 'scale_by_keep' 能否详细说明pytorch和python版本号，不仅主版本号还包括子版本号，谢谢您！
> 
> 我用的是python3.6.8 pytorch1.9.0

。。是不是没装timm包，这个函数是timm包的

**Comment by DotWang** [comment]
> > > 不过我估计哈，你还是用新一点的pytorch版本吧，可能transformer中的一些函数只有新一点的pytorch有，也谢谢你的提醒，我去改一下说明文件
> > 
> > 
> > 我运行还是出错了， AttributeError: 'DropPath' object has no attribute 'scale_by_keep' 能否详细说明pytorch和python版本号，不仅主版本号还包括子版本号，谢谢您！
> > 我用的是python3.6.8 pytorch1.9.0
> 

一般和子版本号没啥关系，这个函数是timm包里边的，你先看看有没有装timm包

**Comment by zgsxwsdxg** [comment]
> > > > 不过我估计哈，你还是用新一点的pytorch版本吧，可能transformer中的一些函数只有新一点的pytorch有，也谢谢你的提醒，我去改一下说明文件
> > > 
> > > 
> > > 我运行还是出错了， AttributeError: 'DropPath' object has no attribute 'scale_by_keep' 能否详细说明pytorch和python版本号，不仅主版本号还包括子版本号，谢谢您！
> > > 我用的是python3.6.8 pytorch1.9.0
> 
> 一般和子版本号没啥关系，这个函数是timm包里边的，你先看看有没有装timm包

装了timm，版本号是0.5.4

你们装的timm是那个版本？

**Comment by DotWang** [comment]
> > > > > 不过我估计哈，你还是用新一点的pytorch版本吧，可能transformer中的一些函数只有新一点的pytorch有，也谢谢你的提醒，我去改一下说明文件
> > > > 
> > > > 
> > > > 我运行还是出错了， AttributeError: 'DropPath' object has no attribute 'scale_by_keep' 能否详细说明pytorch和python版本号，不仅主版本号还包括子版本号，谢谢您！
> > > > 我用的是python3.6.8 pytorch1.9.0
> > 
> > 
> > 一般和子版本号没啥关系，这个函数是timm包里边的，你先看看有没有装timm包
> 
> 装了timm，版本号是0.5.4
> 
> 你们装的timm是那个版本？能不能把readme中install部分完善下，装起来有些包不知道版本号，不好弄，谢谢！

就是0.5.4啊，建议你把错误完整信息放出来，要不然我看不出来啊

**Comment by zgsxwsdxg** [comment]
> > > > > > 不过我估计哈，你还是用新一点的pytorch版本吧，可能transformer中的一些函数只有新一点的pytorch有，也谢谢你的提醒，我去改一下说明文件
> > > > > 
> > > > > 
> > > > > 我运行还是出错了， AttributeError: 'DropPath' object has no attribute 'scale_by_keep' 能否详细说明pytorch和python版本号，不仅主版本号还包括子版本号，谢谢您！
> > > > > 我用的是python3.6.8 pytorch1.9.0
> > > 
> > > 
> > > 一般和子版本号没啥关系，这个函数是timm包里边的，你先看看有没有装timm包
> > 
> > 
> > 装了timm，版本号是0.5.4
> > 你们装的timm是那个版本？能不能把readme中install部分完善下，装起来有些包不知道版本号，不好弄，谢谢！
> 
> 就是0.5.4啊，建议你把错误完整信息放出来，要不然我看不出来啊

Traceback (most recent call last):
  File ".\visualization-src.py", line 56, in <module>
    cd_preds = model(batch_img1, batch_img2)
  File "D:\anaconda3\envs\cdd-pth-1.9-py3.6.8\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\codes\ViTAE-Transformer-Remote-Sensing\ChangeDetection\models\networks.py", line 562, in forward
    x1 = self.forward_single(x1)
  File "D:\codes\ViTAE-Transformer-Remote-Sensing\ChangeDetection\models\networks.py", line 448, in forward_single
    x = self.backbone(x)
  File "D:\anaconda3\envs\cdd-pth-1.9-py3.6.8\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\codes\ViTAE-Transformer-Remote-Sensing\ChangeDetection\models\ViTAE_Window_NoShift\base_model.py", line 325, in forward
    x = self.forward_features(x, Wh, Ww)
  File "D:\codes\ViTAE-Transformer-Remote-Sensing\ChangeDetection\models\ViTAE_Window_NoShift\base_model.py", line 312, in forward_features
    x, Wh, Ww = layer(x, Wh, Ww)
  File "D:\anaconda3\envs\cdd-pth-1.9-py3.6.8\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\codes\ViTAE-Transformer-Remote-Sensing\ChangeDetection\models\ViTAE_Window_NoShift\base_model.py", line 103, in forward
    x, H, W = nc(x, H, W)
  File "D:\anaconda3\envs\cdd-pth-1.9-py3.6.8\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\codes\ViTAE-Transformer-Remote-Sensing\ChangeDetection\models\ViTAE_Window_NoShift\NormalCell.py", line 252, in forward
    convX = self.drop_path(self.gamma2 * self.PCM(shortcut.view(b, H, W, c).permute(0, 3, 1, 2).contiguous()).permute(0, 2, 3, 1).contiguous().view(b, n, c))
  File "D:\anaconda3\envs\cdd-pth-1.9-py3.6.8\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\anaconda3\envs\cdd-pth-1.9-py3.6.8\lib\site-packages\timm\models\layers\drop.py", line 164, in forward
    return drop_path(x, self.drop_prob, self.training, self.scale_by_keep)
  File "D:\anaconda3\envs\cdd-pth-1.9-py3.6.8\lib\site-packages\torch\nn\modules\module.py", line 1131, in __getattr__
    type(self).__name__, name))
AttributeError: 'DropPath' object has no attribute 'scale_by_keep'

**Comment by zgsxwsdxg** [comment]
> 服了，之前我不是提到我现在换了环境了吗，这个代码是在之前的环境的跑通的（不过我现在这个环境也能跑通，可能是因为我中途改了某些东西，这个真不清楚了，目前这个仓库上传的是改之前的，和ViTAE的仓库应该是一套），ViTAE需要的版本你可以参考这个 https://github.com/ViTAE-Transformer/ViTAE-Transformer/tree/main/Image-Classification 中的readme，里边提到timm的版本应该是0.3.4

除了降低timm版本能解决这个问题，还有没有支持timm=0.5.4的代码版本，谢谢

**Comment by DotWang** [comment]
变化检测这部分的代码我后来改了点，但是究竟改了啥就能跑起来timm0.5.4这部分我真忘了。。目前我手头上整套代码文件中包含了我们一个正在进行中的新工作，所以暂时还不方便公开，请见谅

**Comment by zgsxwsdxg** [comment]
> 变化检测这部分的代码我后来改了点，但是究竟改了啥就能跑起来timm0.5.4这部分我真忘了。。目前我手头上整套代码文件中包含了我们一个正在进行中的新工作，所以暂时还不方便公开，请见谅

好的，那么我现在装这个 change detection环境 的话 按https://github.com/ViTAE-Transformer/ViTAE-Transformer/tree/main/Image-Classification 的仓库环境配置pytorch版本和python版本？我刚试了pytorch1.9.0 和python3.6.8无法安装timm=0.3.4，安装时提示要求python版本大于3.7，所以我现在真的迷惑，到底怎么装？装那个版本？但是https://github.com/ViTAE-Transformer/ViTAE-Transformer/tree/main/Image-Classification 的仓库环境给的python=3.7 pytorch=1.8.1，迷糊迷糊

**Comment by zgsxwsdxg** [comment]
> python 3.8
> 
> pytorch 1.9+cu111
> 
> torchvision 0.9.0
> 
> 剩下那几个包无脑装就行，tensorboard是1.15，不过我没看过那些曲线，你也可以不装，把相关语句注释掉

这个给的是 pytorch1.9 python=3.8 迷惑迷惑，

**Comment by DotWang** [comment]
> > python 3.8
> > pytorch 1.9+cu111
> > torchvision 0.9.0
> > 剩下那几个包无脑装就行，tensorboard是1.15，不过我没看过那些曲线，你也可以不装，把相关语句注释掉
> 
> 这个给的是 pytorch1.9 python=3.8 迷惑迷惑，

这个是我现在的环境…

**Comment by DotWang** [comment]
> > 变化检测这部分的代码我后来改了点，但是究竟改了啥就能跑起来timm0.5.4这部分我真忘了。。目前我手头上整套代码文件中包含了我们一个正在进行中的新工作，所以暂时还不方便公开，请见谅
> 
> 好的，那么我现在装这个 change detection环境 的话 按https://github.com/ViTAE-Transformer/ViTAE-Transformer/tree/main/Image-Classification 的仓库环境配置pytorch版本和python版本？我刚试了pytorch1.9.0 和python3.6.8无法安装timm=0.3.4，安装时提示要求python版本大于3.7，所以我现在真的迷惑，到底怎么装？装那个版本？但是https://github.com/ViTAE-Transformer/ViTAE-Transformer/tree/main/Image-Classification 的仓库环境给的python=3.7 pytorch=1.8.1，迷糊迷糊

对，考虑到你这个是原始ViTAE仓库那套，那就按照ViTAE这个吧
