### ISSUE TITLE
模型预训练权重在哪下载

### ISSUE THREAD

**Issue by zgsxwsdxg** [ViTAE-Transformer/ViTAE-Transformer-Remote-Sensing#8]
你好！我在训练是发生找不到权重 VitAE_window/output/ViTAE_Window_NoShift_12_basic_stages4_14_224/epoch100/ViTAE_Window_NoShift_12_basic_stages4_14/default/ckpt.pth

**Comment by DotWang** [comment]
仓库主页

**Comment by zgsxwsdxg** [comment]
> 仓库主页

下载的文件名字是bit-rsp-vitaev2-s-levir-ckpt.pth和VitAE_window/output/ViTAE_Window_NoShift_12_basic_stages4_14_224/epoch100/ViTAE_Window_NoShift_12_basic_stages4_14/default/ckpt.pth 是一个吗？

**Comment by zgsxwsdxg** [comment]
> 仓库主页

   if self.args.mode == 'imp':
            pretrained = '../pretrain_model/ViTAE_Window_NoShift_12_basic_stages4_14_best.pth.tar'
        elif self.args.mode == 'rsp_40':
            pretrained = '../VitAE_window/output/ViTAE_Window_NoShift_12_basic_stages4_14_224/epoch40/ViTAE_Window_NoShift_12_basic_stages4_14/default/ckpt.pth'
        elif self.args.mode == 'rsp_100':
            # pretrained = '../VitAE_window/output/ViTAE_Window_NoShift_12_basic_stages4_14_224/epoch100/ViTAE_Window_NoShift_12_basic_stages4_14/default/ckpt.pth'
            pretrained = 'D:\\codes\\ViTAE-Transformer-Remote-Sensing\\ChangeDetection\\weights\\levir\\3\\bit-rsp-vitaev2-s-levir-ckpt.pth'
        else:
            raise NotImplementedError


        if isinstance(pretrained, str):

            ckpt = torch.load(pretrained, map_location='cpu')

            if 'state_dict' in ckpt:
                _state_dict = ckpt['state_dict']
用下载那个权重bit-rsp-vitaev2-s-levir-ckpt.pth 训练时if 'state_dict' in ckpt: 报错了 提示：
Traceback (most recent call last):
  File "train-tmp.py", line 103, in <module>
    model = load_model(opt, dev)
  File "D:\codes\ViTAE-Transformer-Remote-Sensing\ChangeDetection\utils\helpers.py", line 188, in load_model
    with_pos='learned', enc_depth=1, dec_depth=8).to(device)
  File "D:\codes\ViTAE-Transformer-Remote-Sensing\ChangeDetection\models\networks.py", line 476, in __init__
    if_upsample_2x=if_upsample_2x,
  File "D:\codes\ViTAE-Transformer-Remote-Sensing\ChangeDetection\models\networks.py", line 386, in __init__
    norm_eval=False
  File "D:\codes\ViTAE-Transformer-Remote-Sensing\ChangeDetection\models\ViTAE_Window_NoShift\base_model.py", line 191, in __init__
    self.init_weights()
  File "D:\codes\ViTAE-Transformer-Remote-Sensing\ChangeDetection\models\ViTAE_Window_NoShift\base_model.py", line 210, in init_weights
    if 'state_dict' in ckpt:
TypeError: argument of type 'BASE_Transformer' is not iterable

**Comment by zgsxwsdxg** [comment]
> 仓库主页

你base_model.py文件中有好多预训练权重路径，

        if self.args.mode == 'imp':
            pretrained = '../pretrain_model/ViTAE_Window_NoShift_12_basic_stages4_14_best.pth.tar'
        elif self.args.mode == 'rsp_40':
            pretrained = '../VitAE_window/output/ViTAE_Window_NoShift_12_basic_stages4_14_224/epoch40/ViTAE_Window_NoShift_12_basic_stages4_14/default/ckpt.pth'
        elif self.args.mode == 'rsp_100':
            # pretrained = '../VitAE_window/output/ViTAE_Window_NoShift_12_basic_stages4_14_224/epoch100/ViTAE_Window_NoShift_12_basic_stages4_14/default/ckpt.pth'
            pretrained = 'D:\\codes\\ViTAE-Transformer-Remote-Sensing\\ChangeDetection\\weights\\levir\\3\\bit-rsp-vitaev2-s-levir-ckpt.pth'
        else:
            raise NotImplementedError


我添加了下载的 pretrained = 'D:\\codes\\ViTAE-Transformer-Remote-Sensing\\ChangeDetection\\weights\\levir\\3\\bit-rsp-vitaev2-s-levir-ckpt.pth'

**Comment by DotWang** [comment]
不是那个变化监测的主页，是总的主页

**Comment by DotWang** [comment]
这个不需要了，已经有epoch100的了，文章里边的实验已经表明40的不如100的，所以我就没放

**Comment by zgsxwsdxg** [comment]
> 这个不需要了，已经有epoch100的了，文章里边的实验已经表明40的不如100的，所以我就没放

ok，好的，谢谢。
